apiVersion: v1
kind: Secret
metadata:
  name: mock-project-database-secret
  labels:
    quentindev.io/name: mock-project-database-secret
    app.kubernetes.io/instance: mock-project
    app.kubernetes.io/component: database-service
    app.kubernetes.io/name: mock-project-database-secret
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/part-of: mock-project

data:
  MONGODB_URI: bW9uZ29kYjovL2FkbWluOnBhc3N3b3JkQDEwLjAuMjAuNDQ6MjcwMTcvbW9jay1wcm9qZWN0P2F1dGhTb3VyY2U9YWRtaW4K
  # mongodb://admin:password@10.0.20.44:27017/mock-project?authSource=admin
