name: Setup AWS & Terraform
description: Reusable action to configure AWS credentials and setup Terraform

inputs:
  aws-region:
    description: "AWS Region"
    required: true
  terraform-version:
    description: "Terraform Version"
    required: true
    default: "1.11.2"
  role-to-assume:
    description: "AWS IAM role to assume"
    required: true
    default: "github-actions-role"

runs:
  using: "composite"
  steps:
    - name: Setup NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.role-to-assume }}
        aws-region: ${{ inputs.aws-region }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform-version }}

    - name: Setup tflint
      uses: terraform-linters/setup-tflint@v2.3.0
      with:
        tflint_version: v0.47.0

    - name: Setup terrascan
      uses: accurics/terrascan-action@main
      with:
        terrascan_version: v1.18.0
