apiVersion: v1
kind: Service
metadata:
  name: mock-project-backend-service
  labels:
    quentindev.io/name: mock-project-backend-service
    app.kubernetes.io/instance: mock-project
    app.kubernetes.io/component: backend-service
    app.kubernetes.io/name: mock-project-backend-service
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/part-of: mock-project

spec:
  type: ClusterIP
  ports:
    - port: 8082
      name: be-svc-port
      targetPort: be-port
  selector:
    quentindev.io/name: mock-project-backend-service
