apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - database-service/svc.yml
  - backend-service/svc.yml
  - api-gateway/svc.yml
  - ui-service/svc.yml
  - database-service/secret.yml
  - database-service/deploy.yml
  - backend-service/deploy.yml
  - api-gateway/deploy.yml
  - ui-service/deploy.yml
  - ingress.yml
