apiVersion: v1
kind: ServiceAccount
metadata:
  name: quentin-mock-project
  labels:
    quentindev.io/name: mock-project-service-account
    app.kubernetes.io/instance: mock-project
    app.kubernetes.io/name: mock-project-service-account
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/part-of: mock-project
