name: Terraform Plan
description: Reusable action to run terraform plan

inputs:
  is_destroy:
    description: "Whether to run terraform destroy"
    required: false
    default: "false"
  environment:
    description: "Environment to deploy to (e.g., dev, prod)"
    required: true
    default: dev
  var-file:
    description: "Terraform var file"
    required: false
    default: terraform.tfvars
  output-file:
    description: "Terraform plan output file"
    required: false
    default: tfplan

runs:
  using: "composite"
  steps:
    - name: Terraform Init
      shell: bash
      working-directory: environments/${{ inputs.environment }}
      run: terraform init -upgrade

    - name: Terraform Format & Validate
      shell: bash
      working-directory: environments/${{ inputs.environment }}
      run: |
        terraform fmt -check
        terraform validate

    - name: Terraform Plan (or Destroy Plan)
      shell: bash
      working-directory: environments/${{ inputs.environment }}
      run: |
        if [ "${{ inputs.is_destroy }}" = "true" ]; then
          terraform plan -destroy -out=${{ inputs.output-file}} -input=false -var-file=${{ inputs.var-file }}
        else
          terraform plan -out=${{ inputs.output-file }} -input=false -var-file=${{ inputs.var-file }}
        fi
