name: Terraform Plan
description: Reusable action to run terraform plan

inputs:
  is_destroy:
    description: "Whether to run terraform destroy"
    required: false
    default: "false"
  environment:
    required: true
    description: "Environment to deploy to (e.g., dev, prod)"
    default: dev
  var-file:
    description: "Terraform var file"
    required: false
    default: terraform.tfvars

runs:
  using: "composite"
  steps:
    - name: Terraform Init
      run: terraform init -upgrade
      shell: bash
      working-directory: environments/${{ inputs.environment }}

    - name: Terraform Format & Validate
      run: |
        terraform fmt -check
        terraform validate
      shell: bash
      working-directory: environments/${{ inputs.environment }}

    - name: Terraform Plan (or Destroy Plan)
      run: |
        if [ "${{ inputs.is_destroy }}" == "true" ]; then
          terraform plan -destroy -out=tfplan -input=false -var-file=${{ inputs.var-file }}
        else
          terraform plan -out=tfplan -input=false -var-file=${{ inputs.var-file }}
        fi
      shell: bash
      working-directory: environments/${{ inputs.environment }}
