name: Terraform Plan on PR

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - main

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: infra-ubuntu-24-04

    strategy:
      matrix:
        environment: [dev, prod] # Run plan for both environments

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup AWS and Terraform
        uses: ./.github/actions/setup
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Run Terraform Plan
        uses: ./.github/actions/terraform-plan
        with:
          environment: ${{ matrix.environment }}
          is_destroy: "false"
          var-file: terraform.tfvars
