name: Terraform Apply on Merge to branch main

on:
  push:
    branches:
      - main

jobs:
  terraform-apply:
    name: Terraform Apply
    runs-on: infra-ubuntu-24-04

    strategy:
      matrix:
        environment: [dev] # Run plan for dev only, idealy this will be [dev, prod]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup AWS and Terraform
        uses: ./.github/actions/setup
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Fetch terraform.tfvars from GitHub Secrets
        working-directory: environments/${{ matrix.environment }}
        run: |
          if [ "${{ matrix.environment }}" = "dev" ]; then
            echo "${{ secrets.TFVARS_DEV }}" | base64 -d > terraform.tfvars
          elif [ "${{ matrix.environment }}" = "prod" ]; then
            echo "${{ secrets.TFVARS_PROD }}" | base64 -d > terraform.tfvars
          else
            echo "Unsupported environment: ${{ matrix.environment }}"
            exit 1
          fi

      - name: Run Terraform Plan
        uses: ./.github/actions/terraform-plan
        with:
          environment: ${{ matrix.environment }}
          is_destroy: "false"

      - name: Run Terraform Apply
        working-directory: environments/${{ matrix.environment }}
        run: terraform apply --auto-approve -input=false tfplan