name: Terraform Plan on PR

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - main

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: infra-ubuntu-24-04

    strategy:
      matrix:
        environment: [dev, prod] # Run plan for both environments

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup AWS and Terraform
        uses: ./.github/actions/setup
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Fetch terraform.tfvars from GitHub Secrets
        shell: bash
        working-directory: environments/${{ matrix.environment }}
        run: |
          if [ "${{ matrix.environment }}" = "dev" ]; then
            echo "${{ secrets.TFVARS_DEV }}" | base64 -d > terraform.tfvars
          elif [ "${{ matrix.environment }}" = "prod" ]; then
            echo "${{ secrets.TFVARS_PROD }}" | base64 -d > terraform.tfvars
          else
            echo "Unsupported environment: ${{ matrix.environment }}"
            exit 1
          fi

      - name: Run Terraform Plan
        uses: ./.github/actions/terraform-plan
        with:
          environment: ${{ matrix.environment }}
          is_destroy: "false"
          var-file: terraform.tfvars

      - name: Upload Artifact tfplan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-${{ matrix.environment }}
          path: environments/${{ matrix.environment }}/tfplan
