name: Terraform Plan on PR

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - main

# Add concurrency to prevent multiple runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: infra-ubuntu-24-04
    timeout-minutes: 60

    strategy:
      matrix:
        environment: [dev, prod] # Run plan for both environments

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup AWS and Terraform
        uses: ./.github/actions/setup
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}

      - name: Fetch terraform.tfvars from GitHub Secrets
        working-directory: environments/${{ matrix.environment }}
        run: |
          if [ "${{ matrix.environment }}" = "dev" ]; then
            echo "${{ secrets.TFVARS_DEV }}" | base64 -d > terraform.tfvars
          elif [ "${{ matrix.environment }}" = "prod" ]; then
            echo "${{ secrets.TFVARS_PROD }}" | base64 -d > terraform.tfvars
          else
            echo "Unsupported environment: ${{ matrix.environment }}"
            exit 1
          fi

      - name: Run Terraform Plan
        uses: ./.github/actions/terraform-plan
        with:
          environment: ${{ matrix.environment }}
          is_destroy: false
          var-file: terraform.tfvars
          timeout: 30

      - name: Upload Artifact tfplan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-${{ matrix.environment }}
          path: environments/${{ matrix.environment }}/tfplan
          retention-days: 7
